#if GAME_LANGUAGE == LANGUAGE_SPANISH

	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to Pokémon R.O.W.E!\p"
	.string "This is an Open World version\n"
	.string "of Hoenn.\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This is what we call a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "This world is widely inhabited by\n"
	.string "creatures known as Pokémon.\p"
	.string "We humans live alongside Pokémon,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about Pokémon.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding Pokémon.\p"
	.string "To unravel Pokémon mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "And you are?$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN}\n"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to begin!\p"
	.string "Choose your starting location and\n"
	.string "explore this world as you want.\l"
	.string "A different aventure awaits!\p"
	.string "Well, if you have any questions,\n"
	.string "I'll be expecting them on\l"
	.string "PokéCommunity.$"
#else

gText_Birch_Welcome:: @ 82C897B
	.string "Alhamdulillah! 80 tahun Indonesia merdeka!\p"
	.string "Mempersembahkan Pokémon R.O.W.E!\p"
	.string "Tahap awal terjemahan\n"
	.string "ke dalam Bahasa Indonesia\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "Makhluk ini adalah “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "Masih banyak spesies Pokémon lain\n"
	.string "yang akan kalian jumpai di Hoenn.\p"
	.string "Manusia dan Pokémon hidup berdampingan,\n"
	.string "bersama dalam persahabatan, atau\l"
	.string "gotong royong dalam pekerjaan.\p"
	.string "Dan paling sering, kita sibuk\n"
	.string "melatih diri dalam pertarungan.\p"
	.string "Nah, seberapa dekat pun dengan mereka,\n"
	.string "kita belum mengenal Pokémon seutuhnya.\p"
	.string "Faktanya, masih sangat banyak\n"
	.string "rahasia aneka spesies Pokémon.\p"
	.string "Menguak misteri semua spesies Pokémon,\n"
	.string "adalah tujuan akhir riset yang kulakukan.\l"
	.string "Riset jangka panjang.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "Siapakah kamu?$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Apakah laki-laki?\n"
	.string "atau perempuan?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "Nah.\n"
	.string "Siapakah namamu?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "Jadi namamu {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Oke, baiklah!\p"
	.string "Kamu {PLAYER}{KUN}\n"
	.string "Salam kenal!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "Sekarang apakah kamu siap?\p"
	.string "Petualanganmu di wilayah Hoenn\n"
	.string "akan segera dimulai!\p"
	.string "Silakan pilih lokasi awal\n"
	.string "lalu jelajahilah seluruh Hoenn.\l"
	.string "Singkirkan kegundahan dunia nyata!\p"
	.string "Lupakan sejenak para pejabat korup,\n"
	.string "Optimislah, setelah 80 tahun dirgahayu\l"
	.string "kelak Indonesia lebih baik.$"

#endif
